/*
 * Copyright (C) 2015 Cybernetica
 *
 * Research/Commercial License Usage
 * Licensees holding a valid Research License or Commercial License
 * for the Software may use this file according to the written
 * agreement between you and Cybernetica.
 *
 * GNU General Public License Usage
 * Alternatively, this file may be used under the terms of the GNU
 * General Public License version 3.0 as published by the Free Software
 * Foundation and appearing in the file LICENSE.GPL included in the
 * packaging of this file.  Please review the following information to
 * ensure the GNU General Public License version 3.0 requirements will be
 * met: http://www.gnu.org/copyleft/gpl-3.0.html.
 *
 * For further information, please contact us at sharemind@cyber.ee.
 */

#ifndef SHAREMIND_CSTDINTLITERALS_H
#define SHAREMIND_CSTDINTLITERALS_H

#include <cstdint>
#include "IntegerLiterals.h"


namespace sharemind {

SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int8)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int16)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int32)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int64)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int_fast8)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int_fast16)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int_fast32)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int_fast64)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int_least8)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int_least16)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int_least32)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(int_least64)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(intmax)
SHAREMIND_INTEGERLITERAL_DEFINE_SIGNED_STD(intptr)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint8)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint16)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint32)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint64)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint_fast8)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint_fast16)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint_fast32)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint_fast64)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint_least8)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint_least16)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint_least32)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uint_least64)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uintmax)
SHAREMIND_INTEGERLITERAL_DEFINE_UNSIGNED_STD(uintptr)

} /* namespace sharemind { */

#endif /* #ifndef SHAREMIND_CSTDINTLITERALS_H */
